version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
    command: npm run start:dev
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - 3000:${PORT}
      - 50051:50051
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PORT=${PORT}
      - GRPC_URL=backend:50051

      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - MONGO_URI=mongodb://mongo:27017/${DB_NAME}
    networks:
      - personal-network

  postgres:
    image: postgres:14.3-alpine
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
      interval: 30s
      timeout: 60s
      retries: 10
      start_period: 30s
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
    networks:
      - personal-network

networks:
  personal-network:
    name: personal-network
    driver: bridge
