version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
    command: npm run start:dev
    restart: on-failure
    mem_limit: 512m
    volumes:
      - .:/app
    ports:
      - 3000:${PORT}
      - 50052:50052
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PORT=${PORT}
      - GRPC_URL=backend:50052

      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:${RABBITMQ_PORT}
    networks:
      - personal-network

  postgres:
    image: postgres:14.3-alpine
    restart: always
    mem_limit: 512m
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
      interval: 30s
      timeout: 60s
      retries: 10
      start_period: 30s
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
    networks:
      - personal-network

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    mem_limit: 256m
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
    environment:
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_ERLANG_COOKIE=SQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_VHOST=/
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - personal-network

networks:
  personal-network:
    name: personal-network
    driver: bridge
