export const AUTH_GATEWAY = 'AUTH_GATEWAY';
export const AUTH_QUEUE = 'AUTH';

export const USER_QUEUE = 'USER';

export const DATABASE_GATEWAY = 'DATABASE_GATEWAY';

export const TEMPLATE_ADAPTER = 'TEMPLATE_ADAPTER';
export const QUEUE_ADAPTER = 'QUEUE_ADAPTER';
export const ORM_ADAPTER = 'ORM_ADAPTER';

export const EVENT_DISPATCHER = 'EVENT_DISPATCHER';
