export const MAIL_ADAPTER = 'MAIL_ADAPTER';
export const MAIL_GATEWAY = 'MAIL_GATEWAY';

export const AUTH_ADAPTER = 'AUTH_ADAPTER';
export const AUTH_GATEWAY = 'AUTH_GATEWAY';

export const USER_DATABASE_ADAPTER = 'USER_DATABASE_ADAPTER';
export const USER_REPOSITORY = 'USER_REPOSITORY';
