FROM node:16-alpine AS installer

RUN apk add openssl1.1-compat

WORKDIR /app

COPY ../package.*json .

RUN npm install
RUN npx prisma generate


FROM node:16-alpine AS runner

RUN apk add openssl1.1-compat

WORKDIR /app

COPY --from=installer /app/node_modules ./node_modules
COPY .. .

CMD ["npm", "run", "start:dev"]
