on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  Coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Verify git repository
        uses: actions/checkout@v3

      - name: Install node on version
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run tests and generate coverage
        run: npm run test:cov
        # env:
        #   DATABASE_URL: postgresql://postgres:postgres@localhost:5432/database

      # TODO: Configure new project on SonarCloud before uncommenting this
      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
