on:
  pull_request:
      branches:
        - dev


jobs:
  Automatic-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Verify git repository
        uses: actions/checkout@v3

      - name: Install node on version 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:unit
